[package]
name = "soundboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = "0.5.15"
rodio = "0.15.0"
tokio = { version = "1.21.0", features = ["full"] } # TODO defeature
